/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'SerialMsg'
 * message type.
 */

public class SerialMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 36;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 30;

    /** Create a new SerialMsg of size 36. */
    public SerialMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new SerialMsg of the given data_length. */
    public SerialMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg with the given data_length
     * and base offset.
     */
    public SerialMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg using the given byte array
     * as backing store.
     */
    public SerialMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public SerialMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public SerialMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg embedded in the given message
     * at the given base offset.
     */
    public SerialMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg embedded in the given message
     * at the given base offset and length.
     */
    public SerialMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <SerialMsg> \n";
      try {
        s += "  [type=0x"+Long.toHexString(get_type())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [counter=0x"+Long.toHexString(get_counter())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [payload=";
        for (int i = 0; i < 30; i++) {
          s += "0x"+Long.toHexString(getElement_payload(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: type
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'type' is signed (false).
     */
    public static boolean isSigned_type() {
        return false;
    }

    /**
     * Return whether the field 'type' is an array (false).
     */
    public static boolean isArray_type() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'type'
     */
    public static int offset_type() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'type'
     */
    public static int offsetBits_type() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'type'
     */
    public int get_type() {
        return (int)getUIntBEElement(offsetBits_type(), 16);
    }

    /**
     * Set the value of the field 'type'
     */
    public void set_type(int value) {
        setUIntBEElement(offsetBits_type(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'type'
     */
    public static int size_type() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'type'
     */
    public static int sizeBits_type() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: counter
    //   Field type: long, unsigned
    //   Offset (bits): 16
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'counter' is signed (false).
     */
    public static boolean isSigned_counter() {
        return false;
    }

    /**
     * Return whether the field 'counter' is an array (false).
     */
    public static boolean isArray_counter() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'counter'
     */
    public static int offset_counter() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'counter'
     */
    public static int offsetBits_counter() {
        return 16;
    }

    /**
     * Return the value (as a long) of the field 'counter'
     */
    public long get_counter() {
        return (long)getUIntBEElement(offsetBits_counter(), 32);
    }

    /**
     * Set the value of the field 'counter'
     */
    public void set_counter(long value) {
        setUIntBEElement(offsetBits_counter(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'counter'
     */
    public static int size_counter() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'counter'
     */
    public static int sizeBits_counter() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: payload
    //   Field type: short[], unsigned
    //   Offset (bits): 48
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'payload' is signed (false).
     */
    public static boolean isSigned_payload() {
        return false;
    }

    /**
     * Return whether the field 'payload' is an array (true).
     */
    public static boolean isArray_payload() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'payload'
     */
    public static int offset_payload(int index1) {
        int offset = 48;
        if (index1 < 0 || index1 >= 30) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'payload'
     */
    public static int offsetBits_payload(int index1) {
        int offset = 48;
        if (index1 < 0 || index1 >= 30) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'payload' as a short[]
     */
    public short[] get_payload() {
        short[] tmp = new short[30];
        for (int index0 = 0; index0 < numElements_payload(0); index0++) {
            tmp[index0] = getElement_payload(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'payload' from the given short[]
     */
    public void set_payload(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_payload(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'payload'
     */
    public short getElement_payload(int index1) {
        return (short)getUIntBEElement(offsetBits_payload(index1), 8);
    }

    /**
     * Set an element of the array 'payload'
     */
    public void setElement_payload(int index1, short value) {
        setUIntBEElement(offsetBits_payload(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'payload'
     */
    public static int totalSize_payload() {
        return (240 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'payload'
     */
    public static int totalSizeBits_payload() {
        return 240;
    }

    /**
     * Return the size, in bytes, of each element of the array 'payload'
     */
    public static int elementSize_payload() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'payload'
     */
    public static int elementSizeBits_payload() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'payload'
     */
    public static int numDimensions_payload() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'payload'
     */
    public static int numElements_payload() {
        return 30;
    }

    /**
     * Return the number of elements in the array 'payload'
     * for the given dimension.
     */
    public static int numElements_payload(int dimension) {
      int array_dims[] = { 30,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'payload' with a String
     */
    public void setString_payload(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_payload(i, (short)s.charAt(i));
         }
         setElement_payload(i, (short)0); //null terminate
    }

    /**
     * Read the array 'payload' as a String
     */
    public String getString_payload() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,30)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_payload(i) == (char)0) break;
             carr[i] = (char)getElement_payload(i);
         }
         return new String(carr,0,i);
    }

}
