#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'RadioCountMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 100

# The Active Message type associated with this message.
AM_TYPE = 6

class RadioCountMsg(tinyos.message.Message.Message):
    # Create a new RadioCountMsg of size 100.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=100):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <RadioCountMsg> \n"
        try:
            s += "  [counter=0x%x]\n" % (self.get_counter())
        except:
            pass
        try:
            s += "  [dummy=";
            for i in range(0, 48):
                s += "0x%x " % (self.getElement_dummy(i) & 0xffff)
            s += "]\n";
        except:
            pass
        try:
            s += "  [rssi=0x%x]\n" % (self.get_rssi())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: counter
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'counter' is signed (False).
    #
    def isSigned_counter(self):
        return False
    
    #
    # Return whether the field 'counter' is an array (False).
    #
    def isArray_counter(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'counter'
    #
    def offset_counter(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'counter'
    #
    def offsetBits_counter(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'counter'
    #
    def get_counter(self):
        return self.getUIntElement(self.offsetBits_counter(), 16, 1)
    
    #
    # Set the value of the field 'counter'
    #
    def set_counter(self, value):
        self.setUIntElement(self.offsetBits_counter(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'counter'
    #
    def size_counter(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'counter'
    #
    def sizeBits_counter(self):
        return 16
    
    #
    # Accessor methods for field: dummy
    #   Field type: int[]
    #   Offset (bits): 16
    #   Size of each element (bits): 16
    #

    #
    # Return whether the field 'dummy' is signed (False).
    #
    def isSigned_dummy(self):
        return False
    
    #
    # Return whether the field 'dummy' is an array (True).
    #
    def isArray_dummy(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'dummy'
    #
    def offset_dummy(self, index1):
        offset = 16
        if index1 < 0 or index1 >= 48:
            raise IndexError
        offset += 0 + index1 * 16
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'dummy'
    #
    def offsetBits_dummy(self, index1):
        offset = 16
        if index1 < 0 or index1 >= 48:
            raise IndexError
        offset += 0 + index1 * 16
        return offset
    
    #
    # Return the entire array 'dummy' as a int[]
    #
    def get_dummy(self):
        tmp = [None]*48
        for index0 in range (0, self.numElements_dummy(0)):
                tmp[index0] = self.getElement_dummy(index0)
        return tmp
    
    #
    # Set the contents of the array 'dummy' from the given int[]
    #
    def set_dummy(self, value):
        for index0 in range(0, len(value)):
            self.setElement_dummy(index0, value[index0])

    #
    # Return an element (as a int) of the array 'dummy'
    #
    def getElement_dummy(self, index1):
        return self.getUIntElement(self.offsetBits_dummy(index1), 16, 1)
    
    #
    # Set an element of the array 'dummy'
    #
    def setElement_dummy(self, index1, value):
        self.setUIntElement(self.offsetBits_dummy(index1), 16, value, 1)
    
    #
    # Return the total size, in bytes, of the array 'dummy'
    #
    def totalSize_dummy(self):
        return (768 / 8)
    
    #
    # Return the total size, in bits, of the array 'dummy'
    #
    def totalSizeBits_dummy(self):
        return 768
    
    #
    # Return the size, in bytes, of each element of the array 'dummy'
    #
    def elementSize_dummy(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'dummy'
    #
    def elementSizeBits_dummy(self):
        return 16
    
    #
    # Return the number of dimensions in the array 'dummy'
    #
    def numDimensions_dummy(self):
        return 1
    
    #
    # Return the number of elements in the array 'dummy'
    #
    def numElements_dummy():
        return 48
    
    #
    # Return the number of elements in the array 'dummy'
    # for the given dimension.
    #
    def numElements_dummy(self, dimension):
        array_dims = [ 48,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Accessor methods for field: rssi
    #   Field type: int
    #   Offset (bits): 784
    #   Size (bits): 16
    #

    #
    # Return whether the field 'rssi' is signed (False).
    #
    def isSigned_rssi(self):
        return False
    
    #
    # Return whether the field 'rssi' is an array (False).
    #
    def isArray_rssi(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'rssi'
    #
    def offset_rssi(self):
        return (784 / 8)
    
    #
    # Return the offset (in bits) of the field 'rssi'
    #
    def offsetBits_rssi(self):
        return 784
    
    #
    # Return the value (as a int) of the field 'rssi'
    #
    def get_rssi(self):
        return self.getUIntElement(self.offsetBits_rssi(), 16, 1)
    
    #
    # Set the value of the field 'rssi'
    #
    def set_rssi(self, value):
        self.setUIntElement(self.offsetBits_rssi(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'rssi'
    #
    def size_rssi(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'rssi'
    #
    def sizeBits_rssi(self):
        return 16
    
