/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'RadioCountMsg'
 * message type.
 */

public class RadioCountMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 100;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 6;

    /** Create a new RadioCountMsg of size 100. */
    public RadioCountMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new RadioCountMsg of the given data_length. */
    public RadioCountMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg with the given data_length
     * and base offset.
     */
    public RadioCountMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg using the given byte array
     * as backing store.
     */
    public RadioCountMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public RadioCountMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public RadioCountMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg embedded in the given message
     * at the given base offset.
     */
    public RadioCountMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg embedded in the given message
     * at the given base offset and length.
     */
    public RadioCountMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <RadioCountMsg> \n";
      try {
        s += "  [counter=0x"+Long.toHexString(get_counter())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [dummy=";
        for (int i = 0; i < 48; i++) {
          s += "0x"+Long.toHexString(getElement_dummy(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rssi=0x"+Long.toHexString(get_rssi())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: counter
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'counter' is signed (false).
     */
    public static boolean isSigned_counter() {
        return false;
    }

    /**
     * Return whether the field 'counter' is an array (false).
     */
    public static boolean isArray_counter() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'counter'
     */
    public static int offset_counter() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'counter'
     */
    public static int offsetBits_counter() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'counter'
     */
    public int get_counter() {
        return (int)getUIntBEElement(offsetBits_counter(), 16);
    }

    /**
     * Set the value of the field 'counter'
     */
    public void set_counter(int value) {
        setUIntBEElement(offsetBits_counter(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'counter'
     */
    public static int size_counter() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'counter'
     */
    public static int sizeBits_counter() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: dummy
    //   Field type: int[], unsigned
    //   Offset (bits): 16
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'dummy' is signed (false).
     */
    public static boolean isSigned_dummy() {
        return false;
    }

    /**
     * Return whether the field 'dummy' is an array (true).
     */
    public static boolean isArray_dummy() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'dummy'
     */
    public static int offset_dummy(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 48) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'dummy'
     */
    public static int offsetBits_dummy(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 48) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'dummy' as a int[]
     */
    public int[] get_dummy() {
        int[] tmp = new int[48];
        for (int index0 = 0; index0 < numElements_dummy(0); index0++) {
            tmp[index0] = getElement_dummy(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'dummy' from the given int[]
     */
    public void set_dummy(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_dummy(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'dummy'
     */
    public int getElement_dummy(int index1) {
        return (int)getUIntBEElement(offsetBits_dummy(index1), 16);
    }

    /**
     * Set an element of the array 'dummy'
     */
    public void setElement_dummy(int index1, int value) {
        setUIntBEElement(offsetBits_dummy(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'dummy'
     */
    public static int totalSize_dummy() {
        return (768 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'dummy'
     */
    public static int totalSizeBits_dummy() {
        return 768;
    }

    /**
     * Return the size, in bytes, of each element of the array 'dummy'
     */
    public static int elementSize_dummy() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'dummy'
     */
    public static int elementSizeBits_dummy() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'dummy'
     */
    public static int numDimensions_dummy() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'dummy'
     */
    public static int numElements_dummy() {
        return 48;
    }

    /**
     * Return the number of elements in the array 'dummy'
     * for the given dimension.
     */
    public static int numElements_dummy(int dimension) {
      int array_dims[] = { 48,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rssi
    //   Field type: int, unsigned
    //   Offset (bits): 784
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rssi' is signed (false).
     */
    public static boolean isSigned_rssi() {
        return false;
    }

    /**
     * Return whether the field 'rssi' is an array (false).
     */
    public static boolean isArray_rssi() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rssi'
     */
    public static int offset_rssi() {
        return (784 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rssi'
     */
    public static int offsetBits_rssi() {
        return 784;
    }

    /**
     * Return the value (as a int) of the field 'rssi'
     */
    public int get_rssi() {
        return (int)getUIntBEElement(offsetBits_rssi(), 16);
    }

    /**
     * Set the value of the field 'rssi'
     */
    public void set_rssi(int value) {
        setUIntBEElement(offsetBits_rssi(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'rssi'
     */
    public static int size_rssi() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rssi'
     */
    public static int sizeBits_rssi() {
        return 16;
    }

}
